[tool.poetry]
name = "destinations"
version = "0.1.0"
description = ""
authors = ["Paige <davidsonpaige22@gmail.comgit>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
